name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - setup.cfg
      - tox.ini

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
#          - Windows
#          - MacOs
        py:
# https://github.com/PyCQA/pylint/issues/6535
# waiting for fix ^
#          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Setup
        run: make setup

      - name: Test
        run: make test
